chat/urls.py
from django.contrib import admin
from django.urls import path
from chat.views import ChatView, ConversationView

app_name = 'chat'
urlpatterns = [
    path('chat/', ChatView.as_view(), name='chat_page'),
    path('chat/<str:sender>/', ConversationView.as_view(), name='chat_conversation'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat'), ),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class  Conversation(models.Model):
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender', default=1)
	receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver', default=1)
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True,)

	def __str__(self):
		return "from {} to {}".format(self.sender, self.receiver)

chat/forms.py
from django import forms

from chat.models import Conversation

class ConversationForm(forms.ModelForm):

	class Meta:
		model = Conversation
		fields = ['text']	

chat/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import TemplateView, ListView, View, CreateView
from django.views.generic.edit import ModelFormMixin
from django.db.models import Q
from django.contrib.auth.models import User

from chat.models import Conversation
from chat.forms import ConversationForm

class ChatView(TemplateView):
	template_name = 'chat.html'

	def get_context_data(self, **kwargs):
	    context = super(ChatView, self).get_context_data(**kwargs)
	    context['users'] = User.objects.all()
	    return context

class ConversationView(ListView):
	template_name = 'conversation_list.html'
	model = Conversation
	# form_class = ConversationForm

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)
		context['users'] = User.objects.all()
		return context

	def get_queryset(self):
		sender = get_object_or_404(User, username=self.kwargs.get('sender'))
		messages = self.model.objects.filter(Q(sender=self.request.user, receiver=sender) | Q(sender=sender, receiver=self.request.user)).order_by('-created_time')

		return messages
	
	def post(self, request, *args, **kwargs):
		sender = get_object_or_404(User, username=kwargs.get('sender'))
		instance = self.model.objects.create(**{
				'sender': request.user,
				'receiver': sender,
				'text': request.POST.get('text')
			})


		self.object_list = self.get_queryset()
		context = self.get_context_data()
		return self.render_to_response(context)

chat/templates/chat.html
<html>
	<head>Chat page</head>
	<body>		
		<ul>
			{% for user in users %}
				<li>
					<a href="/chat/{{ user.username }}">
						{{ user }}
					</a>					
				</li>
			{% endfor %}
		</ul>
	</body>
</html>

chat/templates/conversation_list.html
<div>
	<div id="left_side" style="width: 20%;  float: left;">
		<ul>
			{% for user in users %}
				<li>
					<a href="{% url 'chat:chat_conversation' sender=user.username %} ">
						{{ user }}
					</a>					
				</li>
			{% endfor %}
		</ul>
	</div>
	<div id="right_side" style="width: 80%; float: left;">
		<ul style="height: 400px; overflow: scroll;">
			{% for object in object_list %}
				<li style="border: 1px dashed #ccc;">
					<p>
						Sender: {{ object.sender }} at {{ object.created_time }}
					</p>
					<p>
						Text:
						{{ object.text }}
					</p>
				</li>
			{% endfor %}
		</ul>
		<div id="chat-wrapper">
			<div id="chat-list"></div>
			<form id="chat_text_input" action="" method="post">
				{% csrf_token %}
				<textarea name="text" id="" cols="30" rows="10"></textarea>
				<input type="submit">
			</form>
		</div>
	</div>	
</div>